coding_task:
  description: >
    Write python code to achieve this: {assignment}
  expected_output: >
    A text file that includes the code itself, along with the output of the code.Do not include any comments in the code. Just write the working code with the provided class format.Dont add any extra comments or explanations.Dont mention language name on top of the code.
  agent: coder
  output_file: output/code_and_output.txt